# **Python list to store data**

In [8]:
# Concatenating two lists in Python
a = [1, 2]
b = [3, 4]
a + b

[1, 2, 3, 4]

In [9]:
# element wise add operation of two lists
def elemwise_add(v, w):
  return [v_i + w_i for v_i, w_i in zip(v, w)]

c = elemwise_add(a,b)
print(c)

[4, 6]


In [10]:
# vector-like dot operation of two lists
def vector_dot(a,b):
  return sum([i*j for i,j in zip(a,b)])

d = vector_dot(a,b)
print(d)

11


# **Numpy array supports arithmetic operations**

In [11]:
import numpy as np

a_np = np.array([1,2])
b_np = np.array([3,4])

c_np = a_np + b_np
print(c_np)

d_np = np.dot(a_np , b_np)
print(d_np)

# or dot product
d2_np = a_np.dot(b_np)
print(d2_np)

[4 6]
11
11


# **np.dot** vs **np.matmul** vs **np.multiply**

https://mkang32.github.io/python/2020/08/30/numpy-matmul.html

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('np.dot(a, b): ')
print(np.dot(a, b))
print()

print('np.matmul(a, b): ')
print(np.matmul(a, b))
print()

print('np.multiply(a, b): ')
print(np.multiply (a, b))
print()

np.dot(a, b): 
32

np.matmul(a, b): 
32

np.multiply(a, b): 
[ 4 10 18]



In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = np.array([[1], [1], [1]])  # shape (3, 1)

print('np.dot(a, b): ')
print(np.dot(a, b))
print()

print('np.matmul(a, b): ')
print(np.matmul(a, b))
print()

np.dot(a, b): 
[[ 6]
 [15]]

np.matmul(a, b): 
[[ 6]
 [15]]



In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = np.array([[1], [1], [1]])  # shape (3, 1)

print('np.multiply(a, b): ')
print(np.multiply (a, b))
print()

np.multiply(a, b): 


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

# **double colon (::) vs single colon (:) in NumPy**

* ***res = array[x::k]*** which is a slicing operation that prints every kth element from the list/array, starting from the index x


* ***res = array[x:]*** which prints everything after the specified index x, including the value at index x.

* ***res = array[:x]*** which prints everything before the specified index x, but not including the value at index x.

In [15]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
res = arr[2::3]
print(res)
print()

res = arr[2:]
print(res)
print()

res = arr[:2]
print(res)
print()

[3 6 9]

[ 3  4  5  6  7  8  9 10]

[1 2]



# **Caution: python name binding**

In [16]:
e_np = np.array([1,2, 3, 4])
print(e_np)
print(e_np.shape)

[1 2 3 4]
(4,)


In [17]:
f_np = e_np

f_np[1] = 999
print(f_np)

[  1 999   3   4]


In [18]:
print(e_np)

print(id(f_np))
print(id(e_np))

[  1 999   3   4]
132274369922320
132274369922320


In [19]:
# this is because of name binding
a = 2
b = a

print(a)
print(b)

# the address of an object in RAM
print(id(a))
print(id(b))

2
2
11654408
11654408


# **Copy function**

In [20]:
e_np = np.array([1,2, 3, 4])
print(e_np)
print(e_np.shape)

f_np = e_np.copy()
f_np[1] = 999

print(f_np)
print(e_np)

print(id(f_np))
print(id(e_np))

[1 2 3 4]
(4,)
[  1 999   3   4]
[1 2 3 4]
132274360309904
132274369928848


**another examples to show the usefulness of copy**

In [21]:
e_np = np.array([[1,2, 3, 4],[5,6,7,8],[9,10,11,12]])
print(e_np)
print(e_np.shape)
print()

f_np = e_np[:,3]
f_np[1] = 999

print(f_np)
print()

print(e_np)
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[  4 999  12]

[[  1   2   3   4]
 [  5   6   7 999]
 [  9  10  11  12]]



# **Python Tuples**

In [22]:
a = (5,)
print(type(a))
print(a)

b= (5)
print(type(b))
print(b)

c= tuple([5])
print(c)

<class 'tuple'>
(5,)
<class 'int'>
5
(5,)
